
package com.xyw.client.henan;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CsyxzmWebService", targetNamespace = "http://www.xywdzkj.com/csyxzm/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CsyxzmWebService {


    /**
     * 
     * @param rk
     * @return
     *     returns com.xyw.client.henan.RkResponse
     */
    @WebMethod(action = "http://www.xywdzkj.com/csyxzm/#csyxzmRk")
    @WebResult(name = "rkResponse", targetNamespace = "http://www.xywdzkj.com/csyxzm/", partName = "rkResponse")
    public RkResponse csyxzmRk(
        @WebParam(name = "rk", targetNamespace = "http://www.xywdzkj.com/csyxzm/", partName = "rk")
        Rk rk);

    /**
     * 
     * @param fp
     * @return
     *     returns com.xyw.client.henan.FpResponse
     */
    @WebMethod(action = "http://www.xywdzkj.com/csyxzm/#csyxzmFp")
    @WebResult(name = "fpResponse", targetNamespace = "http://www.xywdzkj.com/csyxzm/", partName = "fpResponse")
    public FpResponse csyxzmFp(
        @WebParam(name = "fp", targetNamespace = "http://www.xywdzkj.com/csyxzm/", partName = "fp")
        Fp fp);

    /**
     * 
     * @param dj
     * @return
     *     returns com.xyw.client.henan.DjResponse
     */
    @WebMethod(action = "http://www.xywdzkj.com/csyxzm/#csyxzmDj")
    @WebResult(name = "djResponse", targetNamespace = "http://www.xywdzkj.com/csyxzm/", partName = "djResponse")
    public DjResponse csyxzmDj(
        @WebParam(name = "dj", targetNamespace = "http://www.xywdzkj.com/csyxzm/", partName = "dj")
        Dj dj);

    /**
     * 
     * @param zf
     * @return
     *     returns com.xyw.client.henan.ZfResponse
     */
    @WebMethod(action = "http://www.xywdzkj.com/csyxzm/#csyxzmZf")
    @WebResult(name = "zfResponse", targetNamespace = "http://www.xywdzkj.com/csyxzm/", partName = "zfResponse")
    public ZfResponse csyxzmZf(
        @WebParam(name = "zfRequest", targetNamespace = "http://www.xywdzkj.com/csyxzm/", partName = "zf")
        Zf zf);

    /**
     * 
     * @param zf
     * @return
     *     returns com.xyw.client.henan.ZfResponse
     */
    @WebMethod(action = "http://www.xywdzkj.com/csyxzm/#csyxzmZfcl")
    @WebResult(name = "zfclResponse", targetNamespace = "http://www.xywdzkj.com/csyxzm/", partName = "zfclRequest")
    public ZfResponse csyxzmZfcl(
        @WebParam(name = "zfclRequest", targetNamespace = "http://www.xywdzkj.com/csyxzm/", partName = "zf")
        Zf zf);

    /**
     * 
     * @param fm
     * @return
     *     returns com.xyw.client.henan.FmResponse
     */
    @WebMethod(action = "http://www.xywdzkj.com/csyxzm/#csyxzmFm")
    @WebResult(name = "fmResponse", targetNamespace = "http://www.xywdzkj.com/csyxzm/", partName = "fmRequest")
    public FmResponse csyxzmFm(
        @WebParam(name = "fm", targetNamespace = "http://www.xywdzkj.com/csyxzm/", partName = "fm")
        Fm fm);

    /**
     * 
     * @param sfb
     * @return
     *     returns com.xyw.client.henan.SfbResponse
     */
    @WebMethod(action = "http://www.xywdzkj.com/csyxzm/#csyxzmSfb")
    @WebResult(name = "sfbResponse", targetNamespace = "http://www.xywdzkj.com/csyxzm/", partName = "sfbRequest")
    public SfbResponse csyxzmSfb(
        @WebParam(name = "sfb", targetNamespace = "http://www.xywdzkj.com/csyxzm/", partName = "sfb")
        Sfb sfb);

    /**
     * 
     * @param bfb
     * @return
     *     returns com.xyw.client.henan.BfbResponse
     */
    @WebMethod(action = "http://www.xywdzkj.com/csyxzm/#csyxzmBfb")
    @WebResult(name = "bfbResponse", targetNamespace = "http://www.xywdzkj.com/csyxzm/", partName = "bfbRequest")
    public BfbResponse csyxzmBfb(
        @WebParam(name = "bfb", targetNamespace = "http://www.xywdzkj.com/csyxzm/", partName = "bfb")
        Bfb bfb);
    
    /**
     * 
     * @param hfb
     * @return
     *     returns com.xyw.client.henan.HfbResponse
     */
    @WebMethod(action = "http://www.xywdzkj.com/csyxzm/#csyxzmHfb")
    @WebResult(name = "hfbResponse", targetNamespace = "http://www.xywdzkj.com/csyxzm/", partName = "hfbRequest")
    public HfbResponse csyxzmHfb(
        @WebParam(name = "hfb", targetNamespace = "http://www.xywdzkj.com/csyxzm/", partName = "hfb")
        Hfb hfb);
    
    /**
     * 
     * @param jgw
     * @return
     *     returns com.xyw.client.henan.JgwResponse
     */
    @WebMethod(action = "http://www.xywdzkj.com/csyxzm/#csyxzmJgw")
    @WebResult(name = "jgwResponse", targetNamespace = "http://www.xywdzkj.com/csyxzm/", partName = "jgwRequest")
    public JgwResponse csyxzmJgw(
        @WebParam(name = "jgw", targetNamespace = "http://www.xywdzkj.com/csyxzm/", partName = "jgw")
        Jgw jgw);

}
