
package com.xyw.client.henan;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CsyxzmWebServiceImpl", targetNamespace = "http://www.xywdzkj.com/csyxzm/", wsdlLocation = "http://125.46.49.214/hncsyxzm/CsyxzmWebService41?wsdl")
@HandlerChain(file="handler-chain.xml")
public class CsyxzmWebServiceImpl
    extends Service
{

    private final static URL CSYXZMWEBSERVICEIMPL_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.xyw.client.henan.CsyxzmWebServiceImpl.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.xyw.client.henan.CsyxzmWebServiceImpl.class.getResource(".");
            url = new URL(baseUrl, "http://125.46.49.214/hncsyxzm/CsyxzmWebService41?wsdl");//http://123.161.205.38:8001/hncsyxzm/CsyxzmWebService41?wsdl
//            url = new URL(baseUrl, "http://123.161.205.38:8001/hncsyxzm/CsyxzmWebService41?wsdl");//
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://125.46.49.214/hncsyxzm/CsyxzmWebService41?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CSYXZMWEBSERVICEIMPL_WSDL_LOCATION = url;
    }

    public CsyxzmWebServiceImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CsyxzmWebServiceImpl() {
        super(CSYXZMWEBSERVICEIMPL_WSDL_LOCATION, new QName("http://www.xywdzkj.com/csyxzm/", "CsyxzmWebServiceImpl"));
    }

    /**
     * 
     * @return
     *     returns CsyxzmWebService
     */
    @WebEndpoint(name = "CsyxzmWebServicePort")
    public CsyxzmWebService getCsyxzmWebServicePort() {
        return super.getPort(new QName("http://www.xywdzkj.com/csyxzm/", "CsyxzmWebServicePort"), CsyxzmWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CsyxzmWebService
     */
    @WebEndpoint(name = "CsyxzmWebServicePort")
    public CsyxzmWebService getCsyxzmWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.xywdzkj.com/csyxzm/", "CsyxzmWebServicePort"), CsyxzmWebService.class, features);
    }

}
