package com.xyw.medical.ycfsw.model;

// Generated 2015-4-7 10:19:25 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * VD604Id generated by hbm2java
 */
public class VD604 implements java.io.Serializable {
	private static final long serialVersionUID = -1226774334396469933L;
	private long d60401;
	private long d60402;
	private String d60403;
	private String d60404;
	private Date d60405;
	private String d60406;
	private String d60407;
	private String d60408;
	private int d60409;
	private String d60410;
	private String d60411;
	private String d60412;
	private String d60413;
	private String d60414;
	private String d60415;
	private int d60416;
	private int d60417;
	private int d60418;
	private Date d60419;
	private Date d60420;
	private Date d60421;
	private String d60422;
	private String d60423;
	private String d60424;
	private String d60425;
	private String d60426;
	private String d60427;
	private int d60428;
	private int d60429;
	private String d60430;
	private String d60431;
	private String d60432;
	private String d60433;
	private String d60434;
	private String d60435;
	private String d60436;
	private String d60437;
	private String d60438;
	private String d60439;
	private String d60440;
	private String d60441;
	private String d60442;
	private String d60443;
	private String d60444;
	private String d60445;
	private String d60446;
	private String d60447;
	private String d60448;
	private String d60449;
	private String d60450;
	private String d60451;
	private String d60452;
	private Date d60453;
	private String d60454;
	private String d60455;
	private String d60456;
	private String d60457;
	private String d60458;
	private String d60459;
	private String d60460;
	private String d60461;
	private String d60462;
	private String d60463;
	private String d60464;
	private String d60465;
	private String d60466;
	private String d60467;
	private String d60468;
	private String d60469;
	private String d60470;
	private String d60471;
	private String d60472;
	private String d60473;
	private String d60474;
	private String d60475;
	private String d60476;
	private String d60477;
	private String d60478;
	private String d60479;
	private String d60480;
	private String d60410Zh;
	private String d60411Zh;
	private String d60412Zh;
	private String d60413Zh;
	private String d60415Zh;
	private String d60422Zh;
	private String d60423Zh;
	private String d60424Zh;
	private String d60434Zh;
	private String d60436Zh;
	private String d60438Zh;
	private String d60439Zh;
	private String d60440Zh;
	private String d60441Zh;
	private String d60442Zh;
	private String d60443Zh;
	private String d60444Zh;
	private String d60445Zh;
	private String d60446Zh;
	private String d60447Zh;
	private String d60448Zh;
	private String d60449Zh;
	private String d60405Zh;
	private String d60419Zh;
	private String d60420Zh;
	private String d60421Zh;
	private String d60451Zh;
	private String d60453Zh;
	private String d60426Zh;
	public long getD60401() {
		return d60401;
	}
	public void setD60401(long d60401) {
		this.d60401 = d60401;
	}
	public long getD60402() {
		return d60402;
	}
	public void setD60402(long d60402) {
		this.d60402 = d60402;
	}
	public String getD60403() {
		return d60403;
	}
	public void setD60403(String d60403) {
		this.d60403 = d60403;
	}
	public String getD60404() {
		return d60404;
	}
	public void setD60404(String d60404) {
		this.d60404 = d60404;
	}
	public Date getD60405() {
		return d60405;
	}
	public void setD60405(Date d60405) {
		this.d60405 = d60405;
	}
	public String getD60406() {
		return d60406;
	}
	public void setD60406(String d60406) {
		this.d60406 = d60406;
	}
	public String getD60407() {
		return d60407;
	}
	public void setD60407(String d60407) {
		this.d60407 = d60407;
	}
	public String getD60408() {
		return d60408;
	}
	public void setD60408(String d60408) {
		this.d60408 = d60408;
	}
	public int getD60409() {
		return d60409;
	}
	public void setD60409(int d60409) {
		this.d60409 = d60409;
	}
	public String getD60410() {
		return d60410;
	}
	public void setD60410(String d60410) {
		this.d60410 = d60410;
	}
	public String getD60411() {
		return d60411;
	}
	public void setD60411(String d60411) {
		this.d60411 = d60411;
	}
	public String getD60412() {
		return d60412;
	}
	public void setD60412(String d60412) {
		this.d60412 = d60412;
	}
	public String getD60413() {
		return d60413;
	}
	public void setD60413(String d60413) {
		this.d60413 = d60413;
	}
	public String getD60414() {
		return d60414;
	}
	public void setD60414(String d60414) {
		this.d60414 = d60414;
	}
	public String getD60415() {
		return d60415;
	}
	public void setD60415(String d60415) {
		this.d60415 = d60415;
	}
	public int getD60416() {
		return d60416;
	}
	public void setD60416(int d60416) {
		this.d60416 = d60416;
	}
	public int getD60417() {
		return d60417;
	}
	public void setD60417(int d60417) {
		this.d60417 = d60417;
	}
	public int getD60418() {
		return d60418;
	}
	public void setD60418(int d60418) {
		this.d60418 = d60418;
	}
	public Date getD60419() {
		return d60419;
	}
	public void setD60419(Date d60419) {
		this.d60419 = d60419;
	}
	public Date getD60420() {
		return d60420;
	}
	public void setD60420(Date d60420) {
		this.d60420 = d60420;
	}
	public Date getD60421() {
		return d60421;
	}
	public void setD60421(Date d60421) {
		this.d60421 = d60421;
	}
	public String getD60422() {
		return d60422;
	}
	public void setD60422(String d60422) {
		this.d60422 = d60422;
	}
	public String getD60423() {
		return d60423;
	}
	public void setD60423(String d60423) {
		this.d60423 = d60423;
	}
	public String getD60424() {
		return d60424;
	}
	public void setD60424(String d60424) {
		this.d60424 = d60424;
	}
	public String getD60425() {
		return d60425;
	}
	public void setD60425(String d60425) {
		this.d60425 = d60425;
	}
	public String getD60426() {
		return d60426;
	}
	public void setD60426(String d60426) {
		this.d60426 = d60426;
	}
	public String getD60427() {
		return d60427;
	}
	public void setD60427(String d60427) {
		this.d60427 = d60427;
	}
	public int getD60428() {
		return d60428;
	}
	public void setD60428(int d60428) {
		this.d60428 = d60428;
	}
	public int getD60429() {
		return d60429;
	}
	public void setD60429(int d60429) {
		this.d60429 = d60429;
	}
	public String getD60430() {
		return d60430;
	}
	public void setD60430(String d60430) {
		this.d60430 = d60430;
	}
	public String getD60431() {
		return d60431;
	}
	public void setD60431(String d60431) {
		this.d60431 = d60431;
	}
	public String getD60432() {
		return d60432;
	}
	public void setD60432(String d60432) {
		this.d60432 = d60432;
	}
	public String getD60433() {
		return d60433;
	}
	public void setD60433(String d60433) {
		this.d60433 = d60433;
	}
	public String getD60434() {
		return d60434;
	}
	public void setD60434(String d60434) {
		this.d60434 = d60434;
	}
	public String getD60435() {
		return d60435;
	}
	public void setD60435(String d60435) {
		this.d60435 = d60435;
	}
	public String getD60436() {
		return d60436;
	}
	public void setD60436(String d60436) {
		this.d60436 = d60436;
	}
	public String getD60437() {
		return d60437;
	}
	public void setD60437(String d60437) {
		this.d60437 = d60437;
	}
	public String getD60438() {
		return d60438;
	}
	public void setD60438(String d60438) {
		this.d60438 = d60438;
	}
	public String getD60439() {
		return d60439;
	}
	public void setD60439(String d60439) {
		this.d60439 = d60439;
	}
	public String getD60440() {
		return d60440;
	}
	public void setD60440(String d60440) {
		this.d60440 = d60440;
	}
	public String getD60441() {
		return d60441;
	}
	public void setD60441(String d60441) {
		this.d60441 = d60441;
	}
	public String getD60442() {
		return d60442;
	}
	public void setD60442(String d60442) {
		this.d60442 = d60442;
	}
	public String getD60443() {
		return d60443;
	}
	public void setD60443(String d60443) {
		this.d60443 = d60443;
	}
	public String getD60444() {
		return d60444;
	}
	public void setD60444(String d60444) {
		this.d60444 = d60444;
	}
	public String getD60445() {
		return d60445;
	}
	public void setD60445(String d60445) {
		this.d60445 = d60445;
	}
	public String getD60446() {
		return d60446;
	}
	public void setD60446(String d60446) {
		this.d60446 = d60446;
	}
	public String getD60447() {
		return d60447;
	}
	public void setD60447(String d60447) {
		this.d60447 = d60447;
	}
	public String getD60448() {
		return d60448;
	}
	public void setD60448(String d60448) {
		this.d60448 = d60448;
	}
	public String getD60449() {
		return d60449;
	}
	public void setD60449(String d60449) {
		this.d60449 = d60449;
	}
	public String getD60450() {
		return d60450;
	}
	public void setD60450(String d60450) {
		this.d60450 = d60450;
	}
	public String getD60451() {
		return d60451;
	}
	public void setD60451(String d60451) {
		this.d60451 = d60451;
	}
	public String getD60452() {
		return d60452;
	}
	public void setD60452(String d60452) {
		this.d60452 = d60452;
	}
	public Date getD60453() {
		return d60453;
	}
	public void setD60453(Date d60453) {
		this.d60453 = d60453;
	}
	public String getD60454() {
		return d60454;
	}
	public void setD60454(String d60454) {
		this.d60454 = d60454;
	}
	public String getD60455() {
		return d60455;
	}
	public void setD60455(String d60455) {
		this.d60455 = d60455;
	}
	public String getD60456() {
		return d60456;
	}
	public void setD60456(String d60456) {
		this.d60456 = d60456;
	}
	public String getD60457() {
		return d60457;
	}
	public void setD60457(String d60457) {
		this.d60457 = d60457;
	}
	public String getD60458() {
		return d60458;
	}
	public void setD60458(String d60458) {
		this.d60458 = d60458;
	}
	public String getD60459() {
		return d60459;
	}
	public void setD60459(String d60459) {
		this.d60459 = d60459;
	}
	public String getD60460() {
		return d60460;
	}
	public void setD60460(String d60460) {
		this.d60460 = d60460;
	}
	public String getD60461() {
		return d60461;
	}
	public void setD60461(String d60461) {
		this.d60461 = d60461;
	}
	public String getD60462() {
		return d60462;
	}
	public void setD60462(String d60462) {
		this.d60462 = d60462;
	}
	public String getD60463() {
		return d60463;
	}
	public void setD60463(String d60463) {
		this.d60463 = d60463;
	}
	public String getD60464() {
		return d60464;
	}
	public void setD60464(String d60464) {
		this.d60464 = d60464;
	}
	public String getD60465() {
		return d60465;
	}
	public void setD60465(String d60465) {
		this.d60465 = d60465;
	}
	public String getD60466() {
		return d60466;
	}
	public void setD60466(String d60466) {
		this.d60466 = d60466;
	}
	public String getD60467() {
		return d60467;
	}
	public void setD60467(String d60467) {
		this.d60467 = d60467;
	}
	public String getD60468() {
		return d60468;
	}
	public void setD60468(String d60468) {
		this.d60468 = d60468;
	}
	public String getD60469() {
		return d60469;
	}
	public void setD60469(String d60469) {
		this.d60469 = d60469;
	}
	public String getD60470() {
		return d60470;
	}
	public void setD60470(String d60470) {
		this.d60470 = d60470;
	}
	public String getD60471() {
		return d60471;
	}
	public void setD60471(String d60471) {
		this.d60471 = d60471;
	}
	public String getD60472() {
		return d60472;
	}
	public void setD60472(String d60472) {
		this.d60472 = d60472;
	}
	public String getD60473() {
		return d60473;
	}
	public void setD60473(String d60473) {
		this.d60473 = d60473;
	}
	public String getD60474() {
		return d60474;
	}
	public void setD60474(String d60474) {
		this.d60474 = d60474;
	}
	public String getD60475() {
		return d60475;
	}
	public void setD60475(String d60475) {
		this.d60475 = d60475;
	}
	public String getD60476() {
		return d60476;
	}
	public void setD60476(String d60476) {
		this.d60476 = d60476;
	}
	public String getD60477() {
		return d60477;
	}
	public void setD60477(String d60477) {
		this.d60477 = d60477;
	}
	public String getD60478() {
		return d60478;
	}
	public void setD60478(String d60478) {
		this.d60478 = d60478;
	}
	public String getD60479() {
		return d60479;
	}
	public void setD60479(String d60479) {
		this.d60479 = d60479;
	}
	public String getD60480() {
		return d60480;
	}
	public void setD60480(String d60480) {
		this.d60480 = d60480;
	}
	public String getD60410Zh() {
		return d60410Zh;
	}
	public void setD60410Zh(String d60410Zh) {
		this.d60410Zh = d60410Zh;
	}
	public String getD60411Zh() {
		return d60411Zh;
	}
	public void setD60411Zh(String d60411Zh) {
		this.d60411Zh = d60411Zh;
	}
	public String getD60412Zh() {
		return d60412Zh;
	}
	public void setD60412Zh(String d60412Zh) {
		this.d60412Zh = d60412Zh;
	}
	public String getD60413Zh() {
		return d60413Zh;
	}
	public void setD60413Zh(String d60413Zh) {
		this.d60413Zh = d60413Zh;
	}
	public String getD60415Zh() {
		return d60415Zh;
	}
	public void setD60415Zh(String d60415Zh) {
		this.d60415Zh = d60415Zh;
	}
	public String getD60422Zh() {
		return d60422Zh;
	}
	public void setD60422Zh(String d60422Zh) {
		this.d60422Zh = d60422Zh;
	}
	public String getD60423Zh() {
		return d60423Zh;
	}
	public void setD60423Zh(String d60423Zh) {
		this.d60423Zh = d60423Zh;
	}
	public String getD60424Zh() {
		return d60424Zh;
	}
	public void setD60424Zh(String d60424Zh) {
		this.d60424Zh = d60424Zh;
	}
	public String getD60434Zh() {
		return d60434Zh;
	}
	public void setD60434Zh(String d60434Zh) {
		this.d60434Zh = d60434Zh;
	}
	public String getD60436Zh() {
		return d60436Zh;
	}
	public void setD60436Zh(String d60436Zh) {
		this.d60436Zh = d60436Zh;
	}
	public String getD60438Zh() {
		return d60438Zh;
	}
	public void setD60438Zh(String d60438Zh) {
		this.d60438Zh = d60438Zh;
	}
	public String getD60439Zh() {
		return d60439Zh;
	}
	public void setD60439Zh(String d60439Zh) {
		this.d60439Zh = d60439Zh;
	}
	public String getD60440Zh() {
		return d60440Zh;
	}
	public void setD60440Zh(String d60440Zh) {
		this.d60440Zh = d60440Zh;
	}
	public String getD60441Zh() {
		return d60441Zh;
	}
	public void setD60441Zh(String d60441Zh) {
		this.d60441Zh = d60441Zh;
	}
	public String getD60442Zh() {
		return d60442Zh;
	}
	public void setD60442Zh(String d60442Zh) {
		this.d60442Zh = d60442Zh;
	}
	public String getD60443Zh() {
		return d60443Zh;
	}
	public void setD60443Zh(String d60443Zh) {
		this.d60443Zh = d60443Zh;
	}
	public String getD60444Zh() {
		return d60444Zh;
	}
	public void setD60444Zh(String d60444Zh) {
		this.d60444Zh = d60444Zh;
	}
	public String getD60445Zh() {
		return d60445Zh;
	}
	public void setD60445Zh(String d60445Zh) {
		this.d60445Zh = d60445Zh;
	}
	public String getD60446Zh() {
		return d60446Zh;
	}
	public void setD60446Zh(String d60446Zh) {
		this.d60446Zh = d60446Zh;
	}
	public String getD60447Zh() {
		return d60447Zh;
	}
	public void setD60447Zh(String d60447Zh) {
		this.d60447Zh = d60447Zh;
	}
	public String getD60448Zh() {
		return d60448Zh;
	}
	public void setD60448Zh(String d60448Zh) {
		this.d60448Zh = d60448Zh;
	}
	public String getD60449Zh() {
		return d60449Zh;
	}
	public void setD60449Zh(String d60449Zh) {
		this.d60449Zh = d60449Zh;
	}
	public String getD60405Zh() {
		return d60405Zh;
	}
	public void setD60405Zh(String d60405Zh) {
		this.d60405Zh = d60405Zh;
	}
	public String getD60419Zh() {
		return d60419Zh;
	}
	public void setD60419Zh(String d60419Zh) {
		this.d60419Zh = d60419Zh;
	}
	public String getD60420Zh() {
		return d60420Zh;
	}
	public void setD60420Zh(String d60420Zh) {
		this.d60420Zh = d60420Zh;
	}
	public String getD60421Zh() {
		return d60421Zh;
	}
	public void setD60421Zh(String d60421Zh) {
		this.d60421Zh = d60421Zh;
	}
	public String getD60453Zh() {
		return d60453Zh;
	}
	public void setD60453Zh(String d60453Zh) {
		this.d60453Zh = d60453Zh;
	}
	public String getD60451Zh() {
		return d60451Zh;
	}
	public void setD60451Zh(String d60451Zh) {
		this.d60451Zh = d60451Zh;
	}
	public String getD60426Zh() {
		return d60426Zh;
	}
	public void setD60426Zh(String d60426Zh) {
		this.d60426Zh = d60426Zh;
	}
	
	
	
	
}
