package com.xyw.ws.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import com.xyw.ws.model.Fp;
import com.xyw.ws.model.FpResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CsyxzmWebService", targetNamespace = "http://www.xywdzkj.com/csyxzm/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CsyxzmWebService {


    /**
     * 
     * @param fp
     * @return
     *     returns com.xywdzkj.csyxzm.FpResponse
     */
    @WebMethod(action = "http://www.xywdzkj.com/csyxzm/#csyxzmFp")
    @WebResult(name = "fpResponse", targetNamespace = "http://www.xywdzkj.com/csyxzm/", partName = "fpResponse")
    public FpResponse csyxzmFp(
        @WebParam(name = "fp", targetNamespace = "http://www.xywdzkj.com/csyxzm/", partName = "fp")
        Fp fp);

}
