
package com.xyw.client.fybj.bean;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Test", action = "http://tempuri.org/IService/Test")
    @WebResult(name = "TestResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Test", targetNamespace = "http://tempuri.org/", className = "com.xyw.client.fybj.bean.Test")
    @ResponseWrapper(localName = "TestResponse", targetNamespace = "http://tempuri.org/", className = "com.xyw.client.fybj.bean.TestResponse")
    public String test();

    /**
     * 
     * @param model
     * @param secretKey
     * @return
     *     returns com.xyw.client.fybj.bean.SResult
     */
    @WebMethod(operationName = "Push_LiangBing", action = "http://tempuri.org/IService/Push_LiangBing")
    @WebResult(name = "Push_LiangBingResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Push_LiangBing", targetNamespace = "http://tempuri.org/", className = "com.xyw.client.fybj.bean.PushLiangBing")
    @ResponseWrapper(localName = "Push_LiangBingResponse", targetNamespace = "http://tempuri.org/", className = "com.xyw.client.fybj.bean.PushLiangBingResponse")
    public SResult pushLiangBing(
        @WebParam(name = "SecretKey", targetNamespace = "http://tempuri.org/")
        String secretKey,
        @WebParam(name = "model", targetNamespace = "http://tempuri.org/")
        ModelLiangBing model);

    /**
     * 
     * @param str
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CreateSecretKey", action = "http://tempuri.org/IService/CreateSecretKey")
    @WebResult(name = "CreateSecretKeyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreateSecretKey", targetNamespace = "http://tempuri.org/", className = "com.xyw.client.fybj.bean.CreateSecretKey")
    @ResponseWrapper(localName = "CreateSecretKeyResponse", targetNamespace = "http://tempuri.org/", className = "com.xyw.client.fybj.bean.CreateSecretKeyResponse")
    public String createSecretKey(
        @WebParam(name = "str", targetNamespace = "http://tempuri.org/")
        String str);

}
